package name.medin.tutorial.adf.intro.model.server.serviceinterface;

import java.lang.reflect.Method;

import java.util.List;

import javax.ejb.Remote;
import javax.ejb.Stateless;

import javax.interceptor.Interceptors;

import name.medin.tutorial.adf.intro.model.common.AllJobsViewSDO;
import name.medin.tutorial.adf.intro.model.common.serviceinterface.AppModuleService;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.common.Diagnostic;
import oracle.jbo.common.sdo.SDOHelper;
import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.server.svc.ServiceContextInterceptor;
import oracle.jbo.server.svc.ServiceImpl;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 07 20:44:10 CEST 2014
// ---------------------------------------------------------------------
@Interceptors({ ServiceContextInterceptor.class })
@Stateless(name = "name.medin.tutorial.adf.intro.model.common.AppModuleServiceBean",
           mappedName = "AppModuleServiceBean")
@Remote(AppModuleService.class)
@PortableWebService(targetNamespace = "/name/medin/tutorial/adf/intro/model/common/", serviceName = "AppModuleService",
                    portName = "AppModuleServiceSoapHttpPort",
                    endpointInterface = "name.medin.tutorial.adf.intro.model.common.serviceinterface.AppModuleService")
public class AppModuleServiceImpl extends ServiceImpl implements AppModuleService {
    private static boolean _isInited = false;

    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleServiceImpl() {
        init();
        setApplicationModuleDefName("name.medin.tutorial.adf.intro.model.AppModule");
        setConfigurationName("AppModuleService");
    }

    /**
     * Generated method. Do not modify. Do initialization in the constructor
     */
    protected void init() {
        if (_isInited) {
            return;
        }
        synchronized (AppModuleServiceImpl.class) {
            if (_isInited) {
                return;
            }
            try {
                SDOHelper.INSTANCE.defineSchema("name/medin/tutorial/adf/intro/model/common/serviceinterface/",
                                                "AppModuleService.xsd");
                _isInited = true;
            } catch (Throwable t) {
                ADFLogger.createADFLogger(Diagnostic.SERVINT_RT_LOGGER).severe(t);
            }
        }
    }


    /**
     * findAllJobsView: generated method. Do not modify.
     */
    public List<AllJobsViewSDO> findAllJobsView(FindCriteria findCriteria,
                                                FindControl findControl) throws ServiceException {
        return (List<AllJobsViewSDO>) find(findCriteria, findControl, "AllJobsView", AllJobsViewSDO.class);
    }
}

