package name.medin.tutorial.adf.intro.model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 19 00:36:33 UTC 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CoolJobsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CoolJobsViewImpl() {
    }
}

