package name.medin.tutorial.adf.intro.model.common.serviceinterface;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import name.medin.tutorial.adf.intro.model.common.AllJobsViewSDO;

import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 07 21:32:20 CEST 2014
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace = "/name/medin/tutorial/adf/intro/model/common/", name = "AppModuleService",
                    wsdlLocation = "name/medin/tutorial/adf/intro/model/common/serviceinterface/AppModuleService.wsdl")
@SDODatabinding(schemaLocation = "name/medin/tutorial/adf/intro/model/common/serviceinterface/AppModuleService.xsd")
public interface AppModuleService {
    public static final String NAME = "{/name/medin/tutorial/adf/intro/model/common/}AppModuleService";

    @WebMethod(action = "/name/medin/tutorial/adf/intro/model/common/findAllJobsView",
               operationName = "findAllJobsView")
    @RequestWrapper(targetNamespace = "/name/medin/tutorial/adf/intro/model/common/types/",
                    localName = "findAllJobsView")
    @ResponseWrapper(targetNamespace = "/name/medin/tutorial/adf/intro/model/common/types/",
                     localName = "findAllJobsViewResponse")
    @WebResult(name = "result")
    List<AllJobsViewSDO> findAllJobsView(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                         FindCriteria findCriteria,
                                         @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                         FindControl findControl) throws ServiceException;
}

